# Capture `nu --help` output for tracking flag changes via git diff.
# Update with: `dotnu embeds-update dotnu-captures/nu--help.nu`

nu --help | print $in
# => The nushell language and shell.
# => 
# => Usage:
# =>   nu [options] [script file] [script args]
# => 
# => Options:
# => 
# => General:
# =>   -h, --help
# =>       show this help message
# =>       Example: nu --help
# =>   -v, --version
# =>       print the version
# =>       Example: nu --version
# => 
# => Startup:
# =>   -i, --interactive
# =>       start as an interactive shell
# =>       Example: nu -i
# =>   -l, --login
# =>       start as a login shell
# =>       Example: nu -l
# =>   -c, --commands <string>
# =>       run the given commands and then exit
# =>       Example: nu -c "print 1"
# =>   -e, --execute <string>
# =>       run the given commands and then enter an interactive shell
# =>       Example: nu -e "print 1"
# =>   -m, --table-mode <string>
# =>       the table mode to use. rounded is default.
# =>       Example: nu -m rounded
# =>   --error-style <string>
# =>       the error style to use (fancy or plain). default: fancy
# =>       Example: nu --error-style plain
# =>   --no-newline
# =>       print the result for --commands(-c) without a newline
# =>       Example: nu --no-newline -c "print 1"
# =>   --stdin
# =>       redirect standard input to a command (with `-c`) or a script file
# =>       Example: nu --stdin -c "print $in"
# =>   --testbin <string>
# =>       run an internal test binary (see available bins below)
# =>       Example: nu --testbin cococo
# =>       Available test bins:
# =>       chop -> With no parameters, will chop a character off the end of each line
# =>       cococo -> Cross platform echo using println!()(e.g: nu --testbin cococo a b c)
# =>       echo_env -> Echo's value of env keys from args(e.g: nu --testbin echo_env FOO BAR)
# =>       echo_env_mixed -> Mix echo of env keys from input(e.g: nu --testbin echo_env_mixed out-err FOO BAR; nu --testbin echo_env_mixed err-out FOO BAR)
# =>       echo_env_stderr -> Echo's value of env keys from args to stderr(e.g: nu --testbin echo_env_stderr FOO BAR)
# =>       echo_env_stderr_fail -> Echo's value of env keys from args to stderr, and exit with failure(e.g: nu --testbin echo_env_stderr_fail FOO BAR)
# =>       fail -> Exits with failure code <c>, if not given, fail with code 1(e.g: nu --testbin fail 10)
# =>       iecho -> Another type of echo that outputs a parameter per line, looping infinitely(e.g: nu --testbin iecho 3)
# =>       input_bytes_length -> Prints the number of bytes received on stdin(e.g: 0x[deadbeef] | nu --testbin input_bytes_length)
# =>       meow -> Cross platform cat (open a file, print the contents) using read_to_string and println!()(e.g: nu --testbin meow file.txt)
# =>       meowb -> Cross platform cat (open a file, print the contents) using read() and write_all() / binary(e.g: nu --testbin meowb sample.db)
# =>       nonu -> Cross platform echo but concats arguments without space and NO newline(e.g: nu --testbin nonu a b c)
# =>       nu_repl -> Run a REPL with the given source lines, it must be called with `--testbin=nu_repl`, `--testbin nu_repl` will not work due to argument count logic
# =>       relay -> Relays anything received on stdin to stdout(e.g: 0x[beef] | nu --testbin relay)
# =>       repeat_bytes -> A version of repeater that can output binary data, even null bytes(e.g: nu --testbin repeat_bytes 003d9fbf 10)
# =>       repeater -> Repeat a string or char N times(e.g: nu --testbin repeater a 5)
# =>   --mcp
# =>       start nu's model context protocol server
# =>       Example: nu --mcp
# =>   --mcp-transport <string>
# =>       transport to use for MCP server (stdio or http)
# =>       Example: nu --mcp --mcp-transport http
# =>   --mcp-port <int>
# =>       port for MCP HTTP transport (default 8080)
# =>       Example: nu --mcp --mcp-transport http --mcp-port 3000
# => 
# => Configuration:
# =>   -I, --include-path <string>
# =>       set the NU_LIB_DIRS for the given script (delimited by char record_sep (''))
# =>       Example: nu -I scripts
# =>   -n, --no-config-file
# =>       start with no config file and no env file
# =>       Example: nu --no-config-file
# =>   --no-history
# =>       disable reading and writing to command history
# =>       Example: nu --no-history
# =>   --no-std-lib
# =>       start with no standard library
# =>       Example: nu --no-std-lib
# =>   --config <path>
# =>       start with an alternate config file
# =>       Example: nu --config config.nu
# =>   --env-config <path>
# =>       start with an alternate environment config file
# =>       Example: nu --env-config env.nu
# => 
# => Logging:
# =>   --log-level <string>
# =>       log level for diagnostic logs (error, warn, info, debug, trace). Off by default
# =>       Example: nu --log-level info
# =>   --log-target <string>
# =>       set the target for the log to output. stdout, stderr(default), mixed or file (requires --log-file)
# =>       Example: nu --log-target stdout
# =>   --log-file <path>
# =>       specify a custom log file path (requires --log-target file and --log-level <level>)
# =>       Example: nu --log-target file --log-file ~/.local/share/nushell/nu.log --log-level info
# =>   --log-include <string...>
# =>       set the Rust module prefixes to include from the log output
# =>       Example: nu --log-include info
# =>   --log-exclude <string...>
# =>       set the Rust module prefixes to exclude from the log output
# =>       Example: nu --log-exclude info
# => 
# => IDE:
# =>   --lsp
# =>       start nu's language server protocol
# =>       Example: nu --lsp
# =>   --ide-goto-def <int>
# =>       go to the definition of the item at the given cursor position and file
# =>       Example: nu --ide-goto-def 0 script.nu
# =>   --ide-hover <int>
# =>       give information about the item at the given cursor position and file
# =>       Example: nu --ide-hover 0 script.nu
# =>   --ide-complete <int>
# =>       list completions for the item at the given cursor position and file
# =>       Example: nu --ide-complete 4 script.nu
# =>   --ide-check <int>
# =>       run a diagnostic check on the given source and limit number of errors returned to provided number
# =>       Example: nu --ide-check 100 script.nu
# =>   --ide-ast
# =>       generate the ast on the given source
# =>       Example: nu --ide-ast script.nu
# => 
# => Experimental:
# =>   --experimental-options <string...>
# =>       enable or disable experimental options, use "all" to set all active options
# =>       Example: nu --experimental-options [example=false]
# => 
# => Plugins:
# =>   --plugin-config <path>
# =>       start with an alternate plugin registry file
# =>       Example: nu --plugin-config plugins.msgpackz
# =>   --plugins <path...>
# =>       list of plugin executable files to load (full paths), separately from the registry file
# =>       Example: nu --plugins /path/nu_plugin_one /path/nu_plugin_two

# =>
# =>
# =>
# =>
# =>
